# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [2]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [3]:
# Import torch
import torch

# Create random tensor
tensor_2 = torch.rand(7,7)
tensor_2

tensor([[0.3892, 0.3668, 0.8920, 0.4561, 0.9329, 0.7103, 0.6852],
        [0.7916, 0.3040, 0.7962, 0.2094, 0.0780, 0.3930, 0.6830],
        [0.9897, 0.1443, 0.9028, 0.2505, 0.4458, 0.0768, 0.4345],
        [0.3800, 0.7128, 0.1520, 0.3606, 0.3206, 0.1019, 0.9792],
        [0.3849, 0.8819, 0.6162, 0.0627, 0.6093, 0.6836, 0.8174],
        [0.6153, 0.2979, 0.3635, 0.3385, 0.5467, 0.3117, 0.3543],
        [0.4894, 0.8893, 0.0249, 0.1317, 0.0019, 0.3014, 0.4432]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [4]:
# Create another random tensor
tensor_3 = torch.rand(1,7)
# Perform matrix multiplication
print(tensor_2 @ tensor_3.T)
print(tensor_2.matmul(tensor_3.T))
print(tensor_2.mm(tensor_3.T))

tensor([[1.6845],
        [1.2937],
        [1.1591],
        [1.1372],
        [1.6032],
        [1.1897],
        [1.1386]])
tensor([[1.6845],
        [1.2937],
        [1.1591],
        [1.1372],
        [1.6032],
        [1.1897],
        [1.1386]])
tensor([[1.6845],
        [1.2937],
        [1.1591],
        [1.1372],
        [1.6032],
        [1.1897],
        [1.1386]])


### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [5]:
# Set manual seed
RANDOM_SEED = 0
torch.manual_seed(RANDOM_SEED)
# Create two random tensors
tensor_41 = torch.rand(7, 7)
tensor_42 = torch.rand(1, 7)

# Matrix multiply tensors
print(tensor_41 @ tensor_42.T)
print(tensor_41.matmul(tensor_42.T), tensor_41.mm(tensor_42.T).shape)

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])
tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]]) torch.Size([7, 1])


### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [6]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [7]:
# Set random seed
RANDOM_SEED = 1234
torch.manual_seed(RANDOM_SEED)
# Check for access to GPU
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Device: {device}")
# Create two random tensors on GPU
tensor_61 = torch.rand(2, 3).to(device)
tensor_62 = torch.rand(2, 3).to(device)
tensor_61, tensor_62

Device: cuda


(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [14]:
# Perform matmul on tensor_A and tensor_B
tensor_61.matmul(tensor_62.T), tensor_61.mm(tensor_62.T).size()

(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'),
 torch.Size([2, 2]))

### 8. Find the maximum and minimum values of the output of 7.

In [16]:
# Find max
print(tensor_61.matmul(tensor_62.T).max())
# Find min
print(tensor_61.matmul(tensor_62.T).min())

tensor(0.5617, device='cuda:0')
tensor(0.3647, device='cuda:0')


### 9. Find the maximum and minimum index values of the output of 7.

In [17]:
# Find arg max
print(tensor_61.matmul(tensor_62.T).argmax())

# Find arg min
print(tensor_61.matmul(tensor_62.T).argmin())

tensor(3, device='cuda:0')
tensor(0, device='cuda:0')



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [18]:
# Set seed
RANDOM_SEED = 7
torch.manual_seed(RANDOM_SEED)
# Create random tensor
tensor_10 = torch.rand(1, 1, 1, 10)

# Remove single dimensions
tensor_10_squeeze = tensor_10.squeeze()

# Print out tensors and their shapes
tensor_10, tensor_10.shape, tensor_10_squeeze, tensor_10_squeeze.shape

(tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
            0.3653, 0.8513]]]]),
 torch.Size([1, 1, 1, 10]),
 tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
         0.8513]),
 torch.Size([10]))